#!/usr/bin/env bash

# aws-stop - stop EC2 instance by name
#
#    from: aws-quick-cli
#          https://github.com/robertpeteuil/aws-quick-cli
#
#  Author: Robert Peteuil   @RobertPeteuil
# Version: 0.9.4, 2017-03-23


if [ -z "$1" ] || [ "$1" = "-h" ]; then
  echo -e "STOPS the specified AWS EC2 instance"
  echo -e "\nusage: aws-stop 'instance-name'"
  echo
  echo -e "   instance-name : name assigned to the EC2 instance (REQUIRED)"
  exit 0
fi

InstanceName="$1"

InstanceId=($(aws ec2 describe-instances --filters "Name=tag:Name,Values=${InstanceName}" "Name=instance-state-name,Values=running" --query 'Reservations[*].Instances[].[InstanceId]' --output text))

if [ -n "$InstanceId" ]; then
  aws ec2 stop-instances --instance-ids "$InstanceId" --output text
else
  echo -e "Instance: ${InstanceName} not found runnning - possibly already offline?"
  exit 1
fi

exit 0
