#!/usr/bin/env bash

# aws-start - start EC2 instance by name
#
#    from: Easy-EC2 Utilities
#          https://github.com/robertpeteuil/Easy-EC2
#
#  Author: Robert Peteuil   @RobertPeteuil
# Version: 0.9.1, 2017-03-13


if [ -z "$1" ] || [ "$1" = "-h" ]; then
  echo -e "STARTS the specified AWS EC2 instance"
  echo -e "\nusage: aws-start 'instance-name'"
  echo
  echo -e "   instance-name : name assigned to the EC2 instance (REQUIRED)"
  exit 0
fi

InstanceName="$1"

InstanceId=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=${InstanceName}" "Name=instance-state-name,Values=stopped" --query 'Reservations[*].Instances[].[InstanceId]' --output text)

if [ -n "$InstanceId" ]; then
  aws ec2 start-instances --instance-ids $InstanceId --output text
else
  echo -e "Instance: ${InstanceName} not found stopped - possibly already offline?"
  exit 1
fi

exit 0
