#!/usr/bin/env bash

# aws-info - display info for specified EC2 instance
#
#    from: Easy-EC2 Utilities
#          https://github.com/robertpeteuil/Easy-EC2
#
#  Author: Robert Peteuil   @RobertPeteuil
# Version: 0.9.1, 2017-03-13


# TURN ON COLOR IF POSSIBLE
if test -t 1; then            # check if stdout is a terminal
  ncolors=$(tput colors)    # see if it supports colors
  if test -n "$ncolors" && test $ncolors -ge 8; then
    BLUE="\033[1;34m"
    WHITE="\033[1;37m"
    GREEN="\033[1;32m"
    RED="\033[1;31m"
    YELLOW="\033[1;33m"
    CYAN="\033[1;36m"
  fi
fi

if [ -z "$1" ] || [ "$1" = "-h" ]; then
  echo -e "lists status and information for AWS EC2 instance specified"
  echo -e "\nusage: aws-info [instance-name] || [-i InstanceId]"
  echo
  echo -e "One of these must be specified:"
  echo -e "   instance-name : name assigned to the EC2 instance"
  echo -e "   -i InstanceId : InstanceId of the EC2 instance"
  exit 0 
elif [ "$1" = "-i" ]; then
  InstanceId="$2"
  InstanceName=$(aws ec2 describe-instances --instance-ids "${InstanceId}" --query 'Reservations[*].Instances[].Tags[].[Value]' --output text)
else
  InstanceName="$1"
  InstanceId=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=${InstanceName}" --query 'Reservations[*].Instances[].[InstanceId]' --output text)
fi

InstanceStatus=$(aws ec2 describe-instances --instance-ids "${InstanceId}" --query 'Reservations[*].Instances[].State[].[Name]' --output text)

ImageAMI=($(aws ec2 describe-instances --instance-ids "${InstanceId}" --query 'Reservations[*].Instances[].[ImageId]' --output text))

ImageDescription=($(aws ec2 describe-images --image-ids ${ImageAMI} --query 'Images[*].{Name:Name}' --output text))

case ${InstanceStatus} in
  running)  CLRstatus=${GREEN} ;;
  stopped)  CLRstatus=${RED} ;;
  stopping)  CLRstatus=${YELLOW} ;;
  pending)  CLRstatus=${YELLOW} ;;
  starting)  CLRstatus=${YELLOW} ;;
  *)  CLRstatus=${WHITE} ;;
esac

echo
echo -e "\t${WHITE}Name: ${CYAN}${InstanceName}${WHITE}     ID: ${CYAN}${InstanceId}${WHITE}     Status: ${CLRstatus}${InstanceStatus}"

echo -e "\t${WHITE}AMI: ${CYAN}${ImageAMI}${WHITE}     ${WHITE}AMI Name: ${CYAN}${ImageDescription}${WHITE}\n"

exit 0
