#!/usr/bin/env bash

# aws-start - start EC2 instance by name
#
#    from: aws-quick-cli
#          https://github.com/robertpeteuil/aws-quick-cli
#
#  Author: Robert Peteuil   @RobertPeteuil
#

scriptname="aws-start"

scriptDir=$(reldir=$(dirname -- "$0"; echo x); reldir=${reldir%?x}; cd -- "$reldir" && pwd && echo x); scriptDir=${scriptDir%?x}

if [[ -d "$scriptDir" ]]; then
  cd "$scriptDir" || { echo >&2 "Cannot cd to utility dir"; exit 1; }
  if [[ ! -e "aws-toggle" ]]; then
    echo "Cannot find 'aws-toggle' in $scriptDir."; exit 1
  else
    ./aws-toggle start "$@"
  fi
else
  echo "Cannot find subcommand 'aws-toggle', $scriptDir doesnt exist."; exit 1
fi

exit 0
