#!/usr/bin/env bash

# aws-stop - stop EC2 instance by name
#
#    from: aws-quick-cli
#          https://github.com/robertpeteuil/aws-quick-cli
#
#  Author: Robert Peteuil   @RobertPeteuil
#

scriptname="aws-stop"

# call aws-toggle utility with start action
if [[ $(which aws-toggle) ]]; then
  aws-toggle stop "$@"
else
  echo "Error - required utility (aws-toggle) not found"
  exit 1
fi

exit 0
